// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { claimApprovalStep, createDocumentRequest, decideApprovalStep, getDocument, listDocuments, type Options, processApprovalSla, publishDocumentPdf, releaseApprovalStep, submitForApproval, updateDocumentDraft } from '../sdk.gen';
import type { ClaimApprovalStepData, ClaimApprovalStepError, ClaimApprovalStepResponse, CreateDocumentRequestData, CreateDocumentRequestResponse, DecideApprovalStepData, DecideApprovalStepError, DecideApprovalStepResponse, GetDocumentData, GetDocumentError, GetDocumentResponse, ListDocumentsData, ListDocumentsResponse, ProcessApprovalSlaData, ProcessApprovalSlaError, ProcessApprovalSlaResponse, PublishDocumentPdfData, PublishDocumentPdfError, PublishDocumentPdfResponse, ReleaseApprovalStepData, ReleaseApprovalStepError, ReleaseApprovalStepResponse, SubmitForApprovalData, SubmitForApprovalError, SubmitForApprovalResponse, UpdateDocumentDraftData, UpdateDocumentDraftError, UpdateDocumentDraftResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const listDocumentsQueryKey = (options?: Options<ListDocumentsData>) => createQueryKey('listDocuments', options, ['Documents']);

/**
 * List document routing cases
 */
export const listDocumentsQuery = defineQueryOptions<Options<ListDocumentsData>, ListDocumentsResponse, Error>((options?: Options<ListDocumentsData>) => ({
    key: listDocumentsQueryKey(options),
    query: async (context) => {
        const { data } = await listDocuments({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Submit a freeform document request
 */
export const createDocumentRequestMutation = (options?: Partial<Options<CreateDocumentRequestData>>): UseMutationOptions<CreateDocumentRequestResponse, Options<CreateDocumentRequestData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await createDocumentRequest({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getDocumentQueryKey = (options: Options<GetDocumentData>) => createQueryKey('getDocument', options, ['Documents']);

/**
 * Get a document routing case
 */
export const getDocumentQuery = defineQueryOptions<Options<GetDocumentData>, GetDocumentResponse, GetDocumentError>((options: Options<GetDocumentData>) => ({
    key: getDocumentQueryKey(options),
    query: async (context) => {
        const { data } = await getDocument({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Author or update the draft content
 */
export const updateDocumentDraftMutation = (options?: Partial<Options<UpdateDocumentDraftData>>): UseMutationOptions<UpdateDocumentDraftResponse, Options<UpdateDocumentDraftData>, UpdateDocumentDraftError> => ({
    mutation: async (vars) => {
        const { data } = await updateDocumentDraft({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Move a draft into the approval chain
 */
export const submitForApprovalMutation = (options?: Partial<Options<SubmitForApprovalData>>): UseMutationOptions<SubmitForApprovalResponse, Options<SubmitForApprovalData>, SubmitForApprovalError> => ({
    mutation: async (vars) => {
        const { data } = await submitForApproval({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Approve or reject the current claimed/named approval step
 */
export const decideApprovalStepMutation = (options?: Partial<Options<DecideApprovalStepData>>): UseMutationOptions<DecideApprovalStepResponse, Options<DecideApprovalStepData>, DecideApprovalStepError> => ({
    mutation: async (vars) => {
        const { data } = await decideApprovalStep({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Self-assign a queued pool approval step
 */
export const claimApprovalStepMutation = (options?: Partial<Options<ClaimApprovalStepData>>): UseMutationOptions<ClaimApprovalStepResponse, Options<ClaimApprovalStepData>, ClaimApprovalStepError> => ({
    mutation: async (vars) => {
        const { data } = await claimApprovalStep({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Return a claimed pool step to the queue
 */
export const releaseApprovalStepMutation = (options?: Partial<Options<ReleaseApprovalStepData>>): UseMutationOptions<ReleaseApprovalStepResponse, Options<ReleaseApprovalStepData>, ReleaseApprovalStepError> => ({
    mutation: async (vars) => {
        const { data } = await releaseApprovalStep({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Process SLA timeouts and elevate overdue steps (scheduler / flow entrypoint)
 */
export const processApprovalSlaMutation = (options?: Partial<Options<ProcessApprovalSlaData>>): UseMutationOptions<ProcessApprovalSlaResponse, Options<ProcessApprovalSlaData>, ProcessApprovalSlaError> => ({
    mutation: async (vars) => {
        const { data } = await processApprovalSla({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Render the approved document as PDF and publish to SharePoint
 */
export const publishDocumentPdfMutation = (options?: Partial<Options<PublishDocumentPdfData>>): UseMutationOptions<PublishDocumentPdfResponse, Options<PublishDocumentPdfData>, PublishDocumentPdfError> => ({
    mutation: async (vars) => {
        const { data } = await publishDocumentPdf({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});
