import type { ConnectionProfile } from './connection-config.ts'
import type { DataverseProvisionPlan } from './dataverse-provision-plan.ts'

export interface PaCommand {
  title: string
  command: string
}

/**
 * Builds non-interactive `pa` commands to wire Dataverse tables + SharePoint site.
 * Dataset / org URLs come from the connection profile (custom domains supported).
 */
export function buildPaConnectCommands(
  profile: ConnectionProfile,
  plan: DataverseProvisionPlan,
): PaCommand[] {
  const cloud = profile.powerPlatform.cloud ?? 'public'
  const environmentId = profile.powerPlatform.environmentId
  const envFlag =
    looksReady(environmentId)
      ? ` --environment-id "${environmentId}"`
      : ''
  const cloudFlag = cloud !== 'public' ? ` --cloud ${cloud}` : ''
  const base = `pnpm exec pa`
  const common = `${cloudFlag}${envFlag}`

  const commands: PaCommand[] = [
    {
      title: 'Create SharePoint Online connection (browser sign-in if needed)',
      command: `${base} connection create --connector ${profile.sharePoint.connectorId ?? 'shared_sharepointonline'} --display-name "Document Routing SharePoint"${common}`,
    },
  ]

  for (const table of plan.tableLogicalNames) {
    commands.push({
      title: `Add Dataverse table data source (${table})`,
      command: `${base} app add data-source --connector dataverse --table ${table} --org-url "${profile.dataverse.environmentUrl}"${common}`,
    })
  }

  commands.push({
    title:
      'Add SharePoint library data source (replace CONNECTION_ID from connection create/list)',
    command: `${base} app add data-source --connector ${profile.sharePoint.connectorId ?? 'shared_sharepointonline'} --connection-id CONNECTION_ID --dataset "${profile.sharePoint.siteUrl}" --table "${profile.sharePoint.libraryName}"${common}`,
  })

  return commands
}

function looksReady(environmentId: string): boolean {
  const value = environmentId.trim().toLowerCase()
  return Boolean(value) && !value.includes('replace_me') && !value.includes('example')
}

/**
 * Renders shell-friendly command list for adopters.
 */
export function renderPaCommandsScript(commands: PaCommand[]): string {
  const lines = [
    '#!/usr/bin/env bash',
    '# Generated by pnpm provision — review before running.',
    '# SharePoint --dataset and Dataverse --org-url use your connections.json hosts (custom domains OK).',
    'set -euo pipefail',
    '',
  ]
  for (const item of commands) {
    lines.push(`# ${item.title}`)
    lines.push(item.command)
    lines.push('')
  }
  return `${lines.join('\n')}\n`
}
