import type { ConnectionProfile } from './connection-config.ts';
import type { DataverseProvisionPlan } from './dataverse-provision-plan.ts';
import { assertSafeCliToken, shellQuote } from './shell-quote.ts';

export interface PaCommand {
	title: string;
	command: string;
}

/**
 * Builds non-interactive `pa` commands to wire Dataverse tables + SharePoint site.
 * Dataset / org URLs come from the connection profile (custom domains supported).
 * All interpolated values are shell-quoted; connector/table tokens are validated.
 */
export function buildPaConnectCommands(
	profile: ConnectionProfile,
	plan: DataverseProvisionPlan,
): PaCommand[] {
	const cloud = profile.powerPlatform.cloud ?? 'public';
	const environmentId = profile.powerPlatform.environmentId;
	const envFlag = looksReady(environmentId)
		? ` --environment-id ${shellQuote(environmentId)}`
		: '';
	const cloudFlag = cloud !== 'public' ? ` --cloud ${shellQuote(cloud)}` : '';
	const base = 'pnpm exec pa';
	const common = `${cloudFlag}${envFlag}`;
	const sharePointConnector = assertSafeCliToken(
		profile.sharePoint.connectorId ?? 'shared_sharepointonline',
		'sharePoint.connectorId',
	);

	const commands: PaCommand[] = [
		{
			title: 'Create SharePoint Online connection (browser sign-in if needed)',
			command: `${base} connection create --connector ${sharePointConnector} --display-name ${shellQuote('Document Routing SharePoint')}${common}`,
		},
	];

	for (const table of plan.tableLogicalNames) {
		const safeTable = assertSafeCliToken(table, 'tableLogicalName');
		commands.push({
			title: `Add Dataverse table data source (${safeTable})`,
			command: `${base} app add data-source --connector dataverse --table ${safeTable} --org-url ${shellQuote(profile.dataverse.environmentUrl)}${common}`,
		});
	}

	commands.push({
		title:
			'Add SharePoint library data source (replace CONNECTION_ID from connection create/list)',
		command: `${base} app add data-source --connector ${sharePointConnector} --connection-id CONNECTION_ID --dataset ${shellQuote(profile.sharePoint.siteUrl)} --table ${shellQuote(profile.sharePoint.libraryName)}${common}`,
	});

	return commands;
}

function looksReady(environmentId: string): boolean {
	const value = environmentId.trim().toLowerCase();
	return Boolean(value) && !value.includes('replace_me') && !value.includes('example');
}

/**
 * Renders shell-friendly command list for adopters.
 */
export function renderPaCommandsScript(commands: PaCommand[]): string {
	const lines = [
		'#!/usr/bin/env bash',
		'# Generated by pnpm provision — review before running.',
		'# SharePoint --dataset and Dataverse --org-url use your connections.json hosts (custom domains OK).',
		'# Values are POSIX single-quoted to avoid injection from connection profile fields.',
		'set -euo pipefail',
		'',
	];
	for (const item of commands) {
		lines.push(`# ${item.title}`);
		lines.push(item.command);
		lines.push('');
	}
	return `${lines.join('\n')}\n`;
}
