// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ClaimApprovalStepData, ClaimApprovalStepErrors, ClaimApprovalStepResponses, CreateDocumentRequestData, CreateDocumentRequestErrors, CreateDocumentRequestResponses, DecideApprovalStepData, DecideApprovalStepErrors, DecideApprovalStepResponses, GetDocumentData, GetDocumentErrors, GetDocumentResponses, ListDocumentsData, ListDocumentsResponses, ProcessApprovalSlaData, ProcessApprovalSlaErrors, ProcessApprovalSlaResponses, PublishDocumentPdfData, PublishDocumentPdfErrors, PublishDocumentPdfResponses, ReleaseApprovalStepData, ReleaseApprovalStepErrors, ReleaseApprovalStepResponses, SubmitForApprovalData, SubmitForApprovalErrors, SubmitForApprovalResponses, UpdateDocumentDraftData, UpdateDocumentDraftErrors, UpdateDocumentDraftResponses, WithdrawAndReviseData, WithdrawAndReviseErrors, WithdrawAndReviseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List document routing cases
 */
export const listDocuments = <ThrowOnError extends boolean = false>(options?: Options<ListDocumentsData, ThrowOnError>): RequestResult<ListDocumentsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListDocumentsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents',
    ...options
});

/**
 * Submit a freeform document request
 */
export const createDocumentRequest = <ThrowOnError extends boolean = false>(options: Options<CreateDocumentRequestData, ThrowOnError>): RequestResult<CreateDocumentRequestResponses, CreateDocumentRequestErrors, ThrowOnError> => (options.client ?? client).post<CreateDocumentRequestResponses, CreateDocumentRequestErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a document routing case
 */
export const getDocument = <ThrowOnError extends boolean = false>(options: Options<GetDocumentData, ThrowOnError>): RequestResult<GetDocumentResponses, GetDocumentErrors, ThrowOnError> => (options.client ?? client).get<GetDocumentResponses, GetDocumentErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}',
    ...options
});

/**
 * Author or update the draft content
 */
export const updateDocumentDraft = <ThrowOnError extends boolean = false>(options: Options<UpdateDocumentDraftData, ThrowOnError>): RequestResult<UpdateDocumentDraftResponses, UpdateDocumentDraftErrors, ThrowOnError> => (options.client ?? client).put<UpdateDocumentDraftResponses, UpdateDocumentDraftErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}/draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Move a draft into the approval chain
 *
 * Materializes steps from the document type’s control chain unless
 * `allowApproverOverride` is enabled and `steps` are supplied.
 * Rejects empty chains and unknown document types.
 *
 */
export const submitForApproval = <ThrowOnError extends boolean = false>(options: Options<SubmitForApprovalData, ThrowOnError>): RequestResult<SubmitForApprovalResponses, SubmitForApprovalErrors, ThrowOnError> => (options.client ?? client).post<SubmitForApprovalResponses, SubmitForApprovalErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}/submit-for-approval',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Withdraw review and return to drafting
 *
 * Clears approval steps and returns the case to `drafting` so authors can
 * revise content. Allowed from `in_review`, `rejected`, or `approved`
 * for the requester, author, or collaborators.
 *
 */
export const withdrawAndRevise = <ThrowOnError extends boolean = false>(options: Options<WithdrawAndReviseData, ThrowOnError>): RequestResult<WithdrawAndReviseResponses, WithdrawAndReviseErrors, ThrowOnError> => (options.client ?? client).post<WithdrawAndReviseResponses, WithdrawAndReviseErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}/withdraw-and-revise',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Approve or reject the current claimed/named approval step
 */
export const decideApprovalStep = <ThrowOnError extends boolean = false>(options: Options<DecideApprovalStepData, ThrowOnError>): RequestResult<DecideApprovalStepResponses, DecideApprovalStepErrors, ThrowOnError> => (options.client ?? client).post<DecideApprovalStepResponses, DecideApprovalStepErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}/approvals/{stepId}/decision',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Self-assign a queued pool approval step
 */
export const claimApprovalStep = <ThrowOnError extends boolean = false>(options: Options<ClaimApprovalStepData, ThrowOnError>): RequestResult<ClaimApprovalStepResponses, ClaimApprovalStepErrors, ThrowOnError> => (options.client ?? client).post<ClaimApprovalStepResponses, ClaimApprovalStepErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}/approvals/{stepId}/claim',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Return a claimed pool step to the queue
 */
export const releaseApprovalStep = <ThrowOnError extends boolean = false>(options: Options<ReleaseApprovalStepData, ThrowOnError>): RequestResult<ReleaseApprovalStepResponses, ReleaseApprovalStepErrors, ThrowOnError> => (options.client ?? client).post<ReleaseApprovalStepResponses, ReleaseApprovalStepErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}/approvals/{stepId}/release',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Process SLA timeouts and elevate overdue steps (scheduler / flow entrypoint)
 *
 * Production callers are Cloud Flows under a service identity; they omit `now`.
 * The local mock accepts `now` only when running in development (`import.meta.env.DEV`).
 *
 */
export const processApprovalSla = <ThrowOnError extends boolean = false>(options: Options<ProcessApprovalSlaData, ThrowOnError>): RequestResult<ProcessApprovalSlaResponses, ProcessApprovalSlaErrors, ThrowOnError> => (options.client ?? client).post<ProcessApprovalSlaResponses, ProcessApprovalSlaErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}/approvals/process-sla',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Render the approved document as PDF and publish to SharePoint
 */
export const publishDocumentPdf = <ThrowOnError extends boolean = false>(options: Options<PublishDocumentPdfData, ThrowOnError>): RequestResult<PublishDocumentPdfResponses, PublishDocumentPdfErrors, ThrowOnError> => (options.client ?? client).post<PublishDocumentPdfResponses, PublishDocumentPdfErrors, ThrowOnError>({
    security: [{ name: 'X-Document-Routing-Actor', type: 'apiKey' }],
    url: '/documents/{documentId}/publish',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
