// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateDocumentRequestData, CreateDocumentRequestResponses, DecideApprovalStepData, DecideApprovalStepErrors, DecideApprovalStepResponses, GetDocumentData, GetDocumentErrors, GetDocumentResponses, ListDocumentsData, ListDocumentsResponses, PublishDocumentPdfData, PublishDocumentPdfErrors, PublishDocumentPdfResponses, SubmitForApprovalData, SubmitForApprovalErrors, SubmitForApprovalResponses, UpdateDocumentDraftData, UpdateDocumentDraftErrors, UpdateDocumentDraftResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List document routing cases
 */
export const listDocuments = <ThrowOnError extends boolean = false>(options?: Options<ListDocumentsData, ThrowOnError>): RequestResult<ListDocumentsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListDocumentsResponses, unknown, ThrowOnError>({ url: '/documents', ...options });

/**
 * Submit a freeform document request
 */
export const createDocumentRequest = <ThrowOnError extends boolean = false>(options: Options<CreateDocumentRequestData, ThrowOnError>): RequestResult<CreateDocumentRequestResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateDocumentRequestResponses, unknown, ThrowOnError>({
    url: '/documents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a document routing case
 */
export const getDocument = <ThrowOnError extends boolean = false>(options: Options<GetDocumentData, ThrowOnError>): RequestResult<GetDocumentResponses, GetDocumentErrors, ThrowOnError> => (options.client ?? client).get<GetDocumentResponses, GetDocumentErrors, ThrowOnError>({ url: '/documents/{documentId}', ...options });

/**
 * Author or update the draft content
 */
export const updateDocumentDraft = <ThrowOnError extends boolean = false>(options: Options<UpdateDocumentDraftData, ThrowOnError>): RequestResult<UpdateDocumentDraftResponses, UpdateDocumentDraftErrors, ThrowOnError> => (options.client ?? client).put<UpdateDocumentDraftResponses, UpdateDocumentDraftErrors, ThrowOnError>({
    url: '/documents/{documentId}/draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Move a draft into the approval chain
 */
export const submitForApproval = <ThrowOnError extends boolean = false>(options: Options<SubmitForApprovalData, ThrowOnError>): RequestResult<SubmitForApprovalResponses, SubmitForApprovalErrors, ThrowOnError> => (options.client ?? client).post<SubmitForApprovalResponses, SubmitForApprovalErrors, ThrowOnError>({
    url: '/documents/{documentId}/submit-for-approval',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Approve or reject the current approval step
 */
export const decideApprovalStep = <ThrowOnError extends boolean = false>(options: Options<DecideApprovalStepData, ThrowOnError>): RequestResult<DecideApprovalStepResponses, DecideApprovalStepErrors, ThrowOnError> => (options.client ?? client).post<DecideApprovalStepResponses, DecideApprovalStepErrors, ThrowOnError>({
    url: '/documents/{documentId}/approvals/{stepId}/decision',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Render the approved document as PDF and publish to SharePoint
 */
export const publishDocumentPdf = <ThrowOnError extends boolean = false>(options: Options<PublishDocumentPdfData, ThrowOnError>): RequestResult<PublishDocumentPdfResponses, PublishDocumentPdfErrors, ThrowOnError> => (options.client ?? client).post<PublishDocumentPdfResponses, PublishDocumentPdfErrors, ThrowOnError>({
    url: '/documents/{documentId}/publish',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
