// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | 'https://{environment}.crm.dynamics.com/api/document-routing' | (string & {});
};

export type DocumentStatus = 'requested' | 'drafting' | 'in_review' | 'approved' | 'rejected' | 'published';

export type ApprovalStepStatus = 'waiting' | 'queued' | 'pending' | 'approved' | 'rejected' | 'skipped';

export type ApprovalAssignmentMode = 'named' | 'pool';

export type SubmitForApprovalRequest = {
    steps: Array<ApprovalStepInput>;
    comment?: string;
};

export type ApprovalStepInput = ({
    assignmentMode: 'named';
} & NamedApprovalStepInput) | ({
    assignmentMode: 'pool';
} & PoolApprovalStepInput);

export type NamedApprovalStepInput = {
    assignmentMode: 'named';
    /**
     * Display role for the step (Legal, Compliance, …)
     */
    role?: string;
    /**
     * Hours until SLA timeout from activation/claim
     */
    slaHours?: number;
    assignee: Approver;
    /**
     * Extra members merged into the pool after SLA timeout
     */
    elevationPool?: Array<Approver>;
};

export type PoolApprovalStepInput = {
    assignmentMode: 'pool';
    /**
     * Display role for the step (Legal, Compliance, …)
     */
    role?: string;
    /**
     * Hours until SLA timeout from queue activation/claim
     */
    slaHours?: number;
    /**
     * Eligible claimers for this pool step
     */
    pool: Array<Approver>;
    /**
     * Extra members merged into the pool after SLA timeout
     */
    elevationPool?: Array<Approver>;
};

export type Approver = {
    email: string;
    displayName: string;
    /**
     * e.g. Legal, Compliance, Department Head
     */
    role?: string;
};

export type ApprovalActorRequest = {
    /**
     * Optional comment; actor is the authenticated principal
     */
    comment?: string;
};

export type ApprovalDecisionRequest = {
    decision: 'approve' | 'reject';
    /**
     * Optional comment; actor is the authenticated principal
     */
    comment?: string;
};

export type ProcessSlaRequest = {
    /**
     * Override clock for tests/local demos; production schedulers omit this
     */
    now?: string;
};

export type PublishRequest = {
    sharePointSiteUrl: string;
    libraryName: string;
    /**
     * Optional folder under the library
     */
    folderPath?: string;
    /**
     * Overrides the default PDF file name
     */
    fileName?: string;
};

export type CreateDocumentRequest = {
    title: string;
    /**
     * Document type id from the app config (drives approval chain + draft template)
     */
    documentType: string;
    /**
     * Unstructured request text that authors turn into a draft
     */
    freeformRequest: string;
    priority?: 'low' | 'normal' | 'high';
    /**
     * Target SharePoint site for the final PDF
     */
    requestedPublishSiteUrl?: string;
    /**
     * SharePoint document library display name
     */
    requestedLibraryName?: string;
};

export type UpdateDraftRequest = {
    title: string;
    bodyMarkdown: string;
    /**
     * Optional summary; author is set from the authenticated principal
     */
    summary?: string;
};

export type DocumentSummary = {
    id: string;
    title: string;
    documentType: string;
    status: DocumentStatus;
    requesterEmail: string;
    /**
     * Author collaboration team shared on create for co-editing drafts
     */
    collaboratorEmails?: Array<string>;
    priority?: 'low' | 'normal' | 'high';
    currentApproverEmail?: string;
    currentStepStatus?: ApprovalStepStatus;
    currentStepDueAt?: string;
    currentStepElevated?: boolean;
    /**
     * Eligible claimers when the active step is a pool queue
     */
    currentPoolEmails?: Array<string>;
    createdAt: string;
    updatedAt: string;
};

export type ApprovalStep = {
    id: string;
    order: number;
    assignmentMode: ApprovalAssignmentMode;
    approverEmail?: string;
    approverDisplayName?: string;
    role?: string;
    status: ApprovalStepStatus;
    pool: Array<Approver>;
    elevationPool?: Array<Approver>;
    slaHours?: number;
    dueAt?: string;
    claimedAt?: string;
    elevated: boolean;
    elevatedAt?: string;
    comment?: string;
    decidedAt?: string;
};

export type Document = DocumentSummary & {
    freeformRequest: string;
    draftBodyMarkdown?: string;
    draftSummary?: string;
    authorEmail?: string;
    approvalSteps: Array<ApprovalStep>;
    history: Array<HistoryEvent>;
    publishedPdfUrl?: string;
    sharePointItemId?: string;
    requestedPublishSiteUrl?: string;
    requestedLibraryName?: string;
};

export type HistoryEvent = {
    id: string;
    at: string;
    actorEmail: string;
    action: string;
    message: string;
};

export type PublishResult = {
    document: Document;
    pdfFileName: string;
    sharePointUrl: string;
    sharePointItemId?: string;
    publishedAt: string;
};

export type Error = {
    message: string;
    code?: string;
};

export type DocumentId = string;

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        status?: DocumentStatus;
        /**
         * Filter by configured document type id (policy, sop, …)
         */
        documentType?: string;
        /**
         * Free-text search across title and request body
         */
        q?: string;
    };
    url: '/documents';
};

export type ListDocumentsResponses = {
    /**
     * Document list
     */
    200: {
        items: Array<DocumentSummary>;
    };
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type CreateDocumentRequestData = {
    body: CreateDocumentRequest;
    path?: never;
    query?: never;
    url: '/documents';
};

export type CreateDocumentRequestResponses = {
    /**
     * Created request
     */
    201: Document;
};

export type CreateDocumentRequestResponse = CreateDocumentRequestResponses[keyof CreateDocumentRequestResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}';
};

export type GetDocumentErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Document detail
     */
    200: Document;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type UpdateDocumentDraftData = {
    body: UpdateDraftRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/draft';
};

export type UpdateDocumentDraftErrors = {
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type UpdateDocumentDraftError = UpdateDocumentDraftErrors[keyof UpdateDocumentDraftErrors];

export type UpdateDocumentDraftResponses = {
    /**
     * Updated draft
     */
    200: Document;
};

export type UpdateDocumentDraftResponse = UpdateDocumentDraftResponses[keyof UpdateDocumentDraftResponses];

export type SubmitForApprovalData = {
    body: SubmitForApprovalRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/submit-for-approval';
};

export type SubmitForApprovalErrors = {
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type SubmitForApprovalError = SubmitForApprovalErrors[keyof SubmitForApprovalErrors];

export type SubmitForApprovalResponses = {
    /**
     * Submitted for approval
     */
    200: Document;
};

export type SubmitForApprovalResponse = SubmitForApprovalResponses[keyof SubmitForApprovalResponses];

export type DecideApprovalStepData = {
    body: ApprovalDecisionRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/decision';
};

export type DecideApprovalStepErrors = {
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type DecideApprovalStepError = DecideApprovalStepErrors[keyof DecideApprovalStepErrors];

export type DecideApprovalStepResponses = {
    /**
     * Updated document after decision
     */
    200: Document;
};

export type DecideApprovalStepResponse = DecideApprovalStepResponses[keyof DecideApprovalStepResponses];

export type ClaimApprovalStepData = {
    body: ApprovalActorRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/claim';
};

export type ClaimApprovalStepErrors = {
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type ClaimApprovalStepError = ClaimApprovalStepErrors[keyof ClaimApprovalStepErrors];

export type ClaimApprovalStepResponses = {
    /**
     * Step claimed
     */
    200: Document;
};

export type ClaimApprovalStepResponse = ClaimApprovalStepResponses[keyof ClaimApprovalStepResponses];

export type ReleaseApprovalStepData = {
    body: ApprovalActorRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/release';
};

export type ReleaseApprovalStepErrors = {
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type ReleaseApprovalStepError = ReleaseApprovalStepErrors[keyof ReleaseApprovalStepErrors];

export type ReleaseApprovalStepResponses = {
    /**
     * Step released back to queue
     */
    200: Document;
};

export type ReleaseApprovalStepResponse = ReleaseApprovalStepResponses[keyof ReleaseApprovalStepResponses];

export type ProcessApprovalSlaData = {
    body?: ProcessSlaRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/process-sla';
};

export type ProcessApprovalSlaErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type ProcessApprovalSlaError = ProcessApprovalSlaErrors[keyof ProcessApprovalSlaErrors];

export type ProcessApprovalSlaResponses = {
    /**
     * Document after SLA processing
     */
    200: Document;
};

export type ProcessApprovalSlaResponse = ProcessApprovalSlaResponses[keyof ProcessApprovalSlaResponses];

export type PublishDocumentPdfData = {
    body: PublishRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/publish';
};

export type PublishDocumentPdfErrors = {
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type PublishDocumentPdfError = PublishDocumentPdfErrors[keyof PublishDocumentPdfErrors];

export type PublishDocumentPdfResponses = {
    /**
     * Published document
     */
    200: PublishResult;
};

export type PublishDocumentPdfResponse = PublishDocumentPdfResponses[keyof PublishDocumentPdfResponses];
