// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | 'https://{environment}.crm.dynamics.com/api/document-routing' | (string & {});
};

export type DocumentStatus = 'requested' | 'drafting' | 'in_review' | 'approved' | 'rejected' | 'published';

export type ApprovalStepStatus = 'waiting' | 'queued' | 'pending' | 'approved' | 'rejected' | 'skipped';

export type ApprovalAssignmentMode = 'named' | 'pool';

export type SubmitForApprovalRequest = {
    /**
     * Optional when the server materializes the chain from document-type
     * control data. Required only when `allowApproverOverride` is enabled.
     *
     */
    steps?: Array<ApprovalStepInput>;
    comment?: string;
};

export type ApprovalStepInput = ({
    assignmentMode: 'named';
} & NamedApprovalStepInput) | ({
    assignmentMode: 'pool';
} & PoolApprovalStepInput);

export type NamedApprovalStepInput = {
    assignmentMode: 'named';
    /**
     * Display role for the step (Legal, Compliance, …)
     */
    role?: string;
    /**
     * Hours until SLA timeout from step activation (not reset on claim)
     */
    slaHours?: number;
    assignee: Approver;
    /**
     * Extra members merged into the pool after SLA timeout (named → elevated pool)
     */
    elevationPool?: Array<Approver>;
};

export type PoolApprovalStepInput = {
    assignmentMode: 'pool';
    /**
     * Display role for the step (Legal, Compliance, …)
     */
    role?: string;
    /**
     * Hours until SLA timeout from queue activation (not reset on claim)
     */
    slaHours?: number;
    /**
     * Eligible claimers for this pool step
     */
    pool: Array<Approver>;
    /**
     * Extra members merged into the pool after SLA timeout
     */
    elevationPool?: Array<Approver>;
};

export type Approver = {
    email: string;
    displayName: string;
    /**
     * e.g. Legal, Compliance, Department Head
     */
    role?: string;
};

export type ApprovalActorRequest = {
    /**
     * Optional comment; actor is the authenticated principal
     */
    comment?: string;
};

export type ApprovalDecisionRequest = {
    decision: 'approve' | 'reject';
    /**
     * Optional comment; actor is the authenticated principal
     */
    comment?: string;
};

export type ProcessSlaRequest = {
    /**
     * DEV/test clock override only. Production Cloud Flows omit this.
     * Invalid timestamps are rejected; non-DEV mocks ignore the field.
     *
     */
    now?: string;
};

export type PublishRequest = {
    sharePointSiteUrl: string;
    libraryName: string;
    /**
     * Optional folder under the library
     */
    folderPath?: string;
    /**
     * Overrides the default PDF file name
     */
    fileName?: string;
};

export type CreateDocumentRequest = {
    title: string;
    /**
     * Document type id from the app config (drives approval chain + draft template)
     */
    documentType: string;
    /**
     * Unstructured request text that authors turn into a draft
     */
    freeformRequest: string;
    priority?: 'low' | 'normal' | 'high';
    /**
     * Target SharePoint site for the final PDF
     */
    requestedPublishSiteUrl?: string;
    /**
     * SharePoint document library display name
     */
    requestedLibraryName?: string;
};

export type UpdateDraftRequest = {
    title: string;
    bodyMarkdown: string;
    /**
     * Optional summary; author is set from the authenticated principal
     */
    summary?: string;
};

export type DocumentSummary = {
    id: string;
    title: string;
    documentType: string;
    status: DocumentStatus;
    requesterEmail: string;
    /**
     * Author collaboration team shared on create for co-editing drafts
     */
    collaboratorEmails?: Array<string>;
    priority?: 'low' | 'normal' | 'high';
    currentApproverEmail?: string;
    currentStepStatus?: ApprovalStepStatus;
    currentStepDueAt?: string;
    currentStepElevated?: boolean;
    /**
     * Eligible claimers when the active step is a pool queue
     */
    currentPoolEmails?: Array<string>;
    createdAt: string;
    updatedAt: string;
    /**
     * Incremented on each draft save
     */
    contentRevision?: number;
    /**
     * contentRevision frozen at submit-for-approval
     */
    submittedContentRevision?: number;
};

export type ApprovalStep = {
    id: string;
    order: number;
    assignmentMode: ApprovalAssignmentMode;
    approverEmail?: string;
    approverDisplayName?: string;
    role?: string;
    status: ApprovalStepStatus;
    pool: Array<Approver>;
    elevationPool?: Array<Approver>;
    slaHours?: number;
    /**
     * Immutable SLA deadline set when the step activates
     */
    activateDueAt?: string;
    /**
     * Denormalized mirror of activateDueAt for inbox filters
     */
    dueAt?: string;
    claimedAt?: string;
    elevated: boolean;
    elevatedAt?: string;
    comment?: string;
    decidedAt?: string;
    /**
     * Document contentRevision at submit
     */
    submittedRevision?: number;
    /**
     * contentRevision recorded when this step approved
     */
    approvedRevision?: number;
};

export type Document = DocumentSummary & {
    freeformRequest: string;
    draftBodyMarkdown?: string;
    draftSummary?: string;
    authorEmail?: string;
    contentRevision: number;
    submittedContentRevision?: number;
    approvalSteps: Array<ApprovalStep>;
    history: Array<HistoryEvent>;
    publishedPdfUrl?: string;
    sharePointItemId?: string;
    requestedPublishSiteUrl?: string;
    requestedLibraryName?: string;
};

export type HistoryEvent = {
    id: string;
    at: string;
    actorEmail: string;
    action: string;
    message: string;
};

export type PublishResult = {
    document: Document;
    pdfFileName: string;
    sharePointUrl: string;
    sharePointItemId?: string;
    publishedAt: string;
};

export type ControlChainStep = {
    order: number;
    assignmentMode: ApprovalAssignmentMode;
    role: string;
    slaHours?: number;
    assignee?: Approver;
    /**
     * Key of an approver pool for pool steps
     */
    poolKey?: string;
    elevationPoolKey?: string;
};

export type ControlDocumentType = {
    id: string;
    label: string;
    description: string;
    requestHint: string;
    draftTemplate: string;
    folderPath?: string;
    authorTeamEmails: Array<string>;
    active: boolean;
    policyVersion: number;
    defaultDestinationId?: string;
    approvalChain: Array<ControlChainStep>;
};

export type ControlDocumentTypeWrite = {
    id: string;
    label: string;
    description: string;
    requestHint: string;
    draftTemplate: string;
    folderPath?: string;
    authorTeamEmails?: Array<string>;
    active: boolean;
    policyVersion?: number;
    defaultDestinationId?: string;
    approvalChain: Array<ControlChainStep>;
};

export type ControlApproverPool = {
    id: string;
    key: string;
    name: string;
    description: string;
    members: Array<Approver>;
};

export type ControlApproverPoolWrite = {
    name: string;
    description?: string;
    members: Array<Approver>;
};

export type ControlPublishDestination = {
    id: string;
    name: string;
    siteUrl: string;
    libraryName: string;
    folderPath: string;
    active: boolean;
};

export type ControlPublishDestinationWrite = {
    name: string;
    siteUrl: string;
    libraryName: string;
    folderPath: string;
    active: boolean;
};

export type ControlSettings = {
    /**
     * When true, Admin-authorized limited chain override at submit is allowed.
     * Default false — submit always materializes from control tables.
     *
     */
    allowApproverOverride: boolean;
    collaborationMode: string;
    namedElevationSemantics: 'convert_to_elevated_pool';
};

export type ControlFlowRun = {
    id: string;
    flowName: string;
    status: 'succeeded' | 'failed' | 'running';
    at: string;
    message: string;
};

export type Error = {
    message: string;
    code?: string;
};

export type DocumentId = string;

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        status?: DocumentStatus;
        /**
         * Filter by configured document type id (policy, sop, …)
         */
        documentType?: string;
        /**
         * Free-text search across title and request body
         */
        q?: string;
    };
    url: '/documents';
};

export type ListDocumentsResponses = {
    /**
     * Document list
     */
    200: {
        items: Array<DocumentSummary>;
    };
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type CreateDocumentRequestData = {
    body: CreateDocumentRequest;
    path?: never;
    query?: never;
    url: '/documents';
};

export type CreateDocumentRequestErrors = {
    /**
     * Validation error
     */
    400: Error;
};

export type CreateDocumentRequestError = CreateDocumentRequestErrors[keyof CreateDocumentRequestErrors];

export type CreateDocumentRequestResponses = {
    /**
     * Created request
     */
    201: Document;
};

export type CreateDocumentRequestResponse = CreateDocumentRequestResponses[keyof CreateDocumentRequestResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}';
};

export type GetDocumentErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Document detail
     */
    200: Document;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type UpdateDocumentDraftData = {
    body: UpdateDraftRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/draft';
};

export type UpdateDocumentDraftErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type UpdateDocumentDraftError = UpdateDocumentDraftErrors[keyof UpdateDocumentDraftErrors];

export type UpdateDocumentDraftResponses = {
    /**
     * Updated draft
     */
    200: Document;
};

export type UpdateDocumentDraftResponse = UpdateDocumentDraftResponses[keyof UpdateDocumentDraftResponses];

export type SubmitForApprovalData = {
    body: SubmitForApprovalRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/submit-for-approval';
};

export type SubmitForApprovalErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type SubmitForApprovalError = SubmitForApprovalErrors[keyof SubmitForApprovalErrors];

export type SubmitForApprovalResponses = {
    /**
     * Submitted for approval
     */
    200: Document;
};

export type SubmitForApprovalResponse = SubmitForApprovalResponses[keyof SubmitForApprovalResponses];

export type WithdrawAndReviseData = {
    body?: ApprovalActorRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/withdraw-and-revise';
};

export type WithdrawAndReviseErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type WithdrawAndReviseError = WithdrawAndReviseErrors[keyof WithdrawAndReviseErrors];

export type WithdrawAndReviseResponses = {
    /**
     * Document returned to drafting
     */
    200: Document;
};

export type WithdrawAndReviseResponse = WithdrawAndReviseResponses[keyof WithdrawAndReviseResponses];

export type DecideApprovalStepData = {
    body: ApprovalDecisionRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/decision';
};

export type DecideApprovalStepErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type DecideApprovalStepError = DecideApprovalStepErrors[keyof DecideApprovalStepErrors];

export type DecideApprovalStepResponses = {
    /**
     * Updated document after decision
     */
    200: Document;
};

export type DecideApprovalStepResponse = DecideApprovalStepResponses[keyof DecideApprovalStepResponses];

export type ClaimApprovalStepData = {
    body: ApprovalActorRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/claim';
};

export type ClaimApprovalStepErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type ClaimApprovalStepError = ClaimApprovalStepErrors[keyof ClaimApprovalStepErrors];

export type ClaimApprovalStepResponses = {
    /**
     * Step claimed
     */
    200: Document;
};

export type ClaimApprovalStepResponse = ClaimApprovalStepResponses[keyof ClaimApprovalStepResponses];

export type ReleaseApprovalStepData = {
    body: ApprovalActorRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/release';
};

export type ReleaseApprovalStepErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type ReleaseApprovalStepError = ReleaseApprovalStepErrors[keyof ReleaseApprovalStepErrors];

export type ReleaseApprovalStepResponses = {
    /**
     * Step released back to queue
     */
    200: Document;
};

export type ReleaseApprovalStepResponse = ReleaseApprovalStepResponses[keyof ReleaseApprovalStepResponses];

export type ProcessApprovalSlaData = {
    body?: ProcessSlaRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/process-sla';
};

export type ProcessApprovalSlaErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type ProcessApprovalSlaError = ProcessApprovalSlaErrors[keyof ProcessApprovalSlaErrors];

export type ProcessApprovalSlaResponses = {
    /**
     * Document after SLA processing
     */
    200: Document;
};

export type ProcessApprovalSlaResponse = ProcessApprovalSlaResponses[keyof ProcessApprovalSlaResponses];

export type PublishDocumentPdfData = {
    body: PublishRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/publish';
};

export type PublishDocumentPdfErrors = {
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type PublishDocumentPdfError = PublishDocumentPdfErrors[keyof PublishDocumentPdfErrors];

export type PublishDocumentPdfResponses = {
    /**
     * Published document
     */
    200: PublishResult;
};

export type PublishDocumentPdfResponse = PublishDocumentPdfResponses[keyof PublishDocumentPdfResponses];

export type ListDocumentTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/document-types';
};

export type ListDocumentTypesResponses = {
    /**
     * Document type catalog
     */
    200: {
        items: Array<ControlDocumentType>;
    };
};

export type ListDocumentTypesResponse = ListDocumentTypesResponses[keyof ListDocumentTypesResponses];

export type CreateDocumentTypeData = {
    body: ControlDocumentTypeWrite;
    path?: never;
    query?: never;
    url: '/control/document-types';
};

export type CreateDocumentTypeErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type CreateDocumentTypeError = CreateDocumentTypeErrors[keyof CreateDocumentTypeErrors];

export type CreateDocumentTypeResponses = {
    /**
     * Created
     */
    201: ControlDocumentType;
};

export type CreateDocumentTypeResponse = CreateDocumentTypeResponses[keyof CreateDocumentTypeResponses];

export type DeactivateDocumentTypeData = {
    body?: never;
    path: {
        typeId: string;
    };
    query?: never;
    url: '/control/document-types/{typeId}';
};

export type DeactivateDocumentTypeErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeactivateDocumentTypeError = DeactivateDocumentTypeErrors[keyof DeactivateDocumentTypeErrors];

export type DeactivateDocumentTypeResponses = {
    /**
     * Deactivated
     */
    200: ControlDocumentType;
};

export type DeactivateDocumentTypeResponse = DeactivateDocumentTypeResponses[keyof DeactivateDocumentTypeResponses];

export type GetDocumentTypeConfigData = {
    body?: never;
    path: {
        typeId: string;
    };
    query?: never;
    url: '/control/document-types/{typeId}';
};

export type GetDocumentTypeConfigErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetDocumentTypeConfigError = GetDocumentTypeConfigErrors[keyof GetDocumentTypeConfigErrors];

export type GetDocumentTypeConfigResponses = {
    /**
     * Document type
     */
    200: ControlDocumentType;
};

export type GetDocumentTypeConfigResponse = GetDocumentTypeConfigResponses[keyof GetDocumentTypeConfigResponses];

export type UpdateDocumentTypeData = {
    body: ControlDocumentTypeWrite;
    path: {
        typeId: string;
    };
    query?: never;
    url: '/control/document-types/{typeId}';
};

export type UpdateDocumentTypeErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type UpdateDocumentTypeError = UpdateDocumentTypeErrors[keyof UpdateDocumentTypeErrors];

export type UpdateDocumentTypeResponses = {
    /**
     * Updated
     */
    200: ControlDocumentType;
};

export type UpdateDocumentTypeResponse = UpdateDocumentTypeResponses[keyof UpdateDocumentTypeResponses];

export type ListApproverPoolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/approver-pools';
};

export type ListApproverPoolsErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type ListApproverPoolsError = ListApproverPoolsErrors[keyof ListApproverPoolsErrors];

export type ListApproverPoolsResponses = {
    /**
     * Pools
     */
    200: {
        items: Array<ControlApproverPool>;
    };
};

export type ListApproverPoolsResponse = ListApproverPoolsResponses[keyof ListApproverPoolsResponses];

export type CreateApproverPoolData = {
    body: ControlApproverPoolWrite;
    path?: never;
    query?: never;
    url: '/control/approver-pools';
};

export type CreateApproverPoolErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type CreateApproverPoolError = CreateApproverPoolErrors[keyof CreateApproverPoolErrors];

export type CreateApproverPoolResponses = {
    /**
     * Created
     */
    201: ControlApproverPool;
};

export type CreateApproverPoolResponse = CreateApproverPoolResponses[keyof CreateApproverPoolResponses];

export type DeleteApproverPoolData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/control/approver-pools/{poolId}';
};

export type DeleteApproverPoolErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type DeleteApproverPoolError = DeleteApproverPoolErrors[keyof DeleteApproverPoolErrors];

export type DeleteApproverPoolResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteApproverPoolResponse = DeleteApproverPoolResponses[keyof DeleteApproverPoolResponses];

export type UpdateApproverPoolData = {
    body: ControlApproverPoolWrite;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/control/approver-pools/{poolId}';
};

export type UpdateApproverPoolErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type UpdateApproverPoolError = UpdateApproverPoolErrors[keyof UpdateApproverPoolErrors];

export type UpdateApproverPoolResponses = {
    /**
     * Updated
     */
    200: ControlApproverPool;
};

export type UpdateApproverPoolResponse = UpdateApproverPoolResponses[keyof UpdateApproverPoolResponses];

export type ListPublishDestinationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/publish-destinations';
};

export type ListPublishDestinationsResponses = {
    /**
     * Destinations
     */
    200: {
        items: Array<ControlPublishDestination>;
    };
};

export type ListPublishDestinationsResponse = ListPublishDestinationsResponses[keyof ListPublishDestinationsResponses];

export type CreatePublishDestinationData = {
    body: ControlPublishDestinationWrite;
    path?: never;
    query?: never;
    url: '/control/publish-destinations';
};

export type CreatePublishDestinationErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type CreatePublishDestinationError = CreatePublishDestinationErrors[keyof CreatePublishDestinationErrors];

export type CreatePublishDestinationResponses = {
    /**
     * Created
     */
    201: ControlPublishDestination;
};

export type CreatePublishDestinationResponse = CreatePublishDestinationResponses[keyof CreatePublishDestinationResponses];

export type DeactivatePublishDestinationData = {
    body?: never;
    path: {
        destinationId: string;
    };
    query?: never;
    url: '/control/publish-destinations/{destinationId}';
};

export type DeactivatePublishDestinationErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeactivatePublishDestinationError = DeactivatePublishDestinationErrors[keyof DeactivatePublishDestinationErrors];

export type DeactivatePublishDestinationResponses = {
    /**
     * Deactivated
     */
    200: ControlPublishDestination;
};

export type DeactivatePublishDestinationResponse = DeactivatePublishDestinationResponses[keyof DeactivatePublishDestinationResponses];

export type UpdatePublishDestinationData = {
    body: ControlPublishDestinationWrite;
    path: {
        destinationId: string;
    };
    query?: never;
    url: '/control/publish-destinations/{destinationId}';
};

export type UpdatePublishDestinationErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type UpdatePublishDestinationError = UpdatePublishDestinationErrors[keyof UpdatePublishDestinationErrors];

export type UpdatePublishDestinationResponses = {
    /**
     * Updated
     */
    200: ControlPublishDestination;
};

export type UpdatePublishDestinationResponse = UpdatePublishDestinationResponses[keyof UpdatePublishDestinationResponses];

export type GetControlSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/settings';
};

export type GetControlSettingsErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type GetControlSettingsError = GetControlSettingsErrors[keyof GetControlSettingsErrors];

export type GetControlSettingsResponses = {
    /**
     * Settings
     */
    200: ControlSettings;
};

export type GetControlSettingsResponse = GetControlSettingsResponses[keyof GetControlSettingsResponses];

export type UpdateControlSettingsData = {
    body: ControlSettings;
    path?: never;
    query?: never;
    url: '/control/settings';
};

export type UpdateControlSettingsErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type UpdateControlSettingsError = UpdateControlSettingsErrors[keyof UpdateControlSettingsErrors];

export type UpdateControlSettingsResponses = {
    /**
     * Updated settings
     */
    200: ControlSettings;
};

export type UpdateControlSettingsResponse = UpdateControlSettingsResponses[keyof UpdateControlSettingsResponses];

export type ListFlowRunsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/flow-runs';
};

export type ListFlowRunsErrors = {
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type ListFlowRunsError = ListFlowRunsErrors[keyof ListFlowRunsErrors];

export type ListFlowRunsResponses = {
    /**
     * Flow runs
     */
    200: {
        items: Array<ControlFlowRun>;
    };
};

export type ListFlowRunsResponse = ListFlowRunsResponses[keyof ListFlowRunsResponses];
