// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | 'https://{environment}.crm.dynamics.com/api/document-routing' | (string & {});
};

export type Principal = {
    email: string;
    /**
     * Effective Document Routing role tokens for UI / mock gating
     */
    roles: Array<'user' | 'author' | 'approver' | 'publisher' | 'admin'>;
    /**
     * Optional Dataverse security role display names
     */
    securityRoleNames?: Array<string>;
};

export type DocumentStatus = 'requested' | 'drafting' | 'in_review' | 'approved' | 'rejected' | 'published' | 'superseded' | 'abandoned';

export type ApprovalStepStatus = 'waiting' | 'queued' | 'pending' | 'approved' | 'rejected' | 'skipped';

export type ApprovalAssignmentMode = 'named' | 'pool';

export type SubmitForApprovalRequest = {
    /**
     * Optional when the server materializes the chain from document-type
     * control data. Required only when `allowApproverOverride` is enabled.
     *
     */
    steps?: Array<ApprovalStepInput>;
    comment?: string;
};

export type ApprovalStepInput = ({
    assignmentMode: 'named';
} & NamedApprovalStepInput) | ({
    assignmentMode: 'pool';
} & PoolApprovalStepInput);

export type NamedApprovalStepInput = {
    assignmentMode: 'named';
    /**
     * Display role for the step (Legal, Compliance, …)
     */
    role?: string;
    /**
     * Hours until SLA timeout from step activation (not reset on claim)
     */
    slaHours?: number;
    authorityLevel?: AuthorityLevel;
    commentPolicy?: CommentPolicy;
    assignee: Approver;
    /**
     * Extra members merged into the pool after SLA timeout (named → elevated pool)
     */
    elevationPool?: Array<Approver>;
};

export type PoolApprovalStepInput = {
    assignmentMode: 'pool';
    /**
     * Display role for the step (Legal, Compliance, …)
     */
    role?: string;
    /**
     * Hours until SLA timeout from queue activation (not reset on claim)
     */
    slaHours?: number;
    authorityLevel?: AuthorityLevel;
    commentPolicy?: CommentPolicy;
    /**
     * Eligible claimers for this pool step
     */
    pool: Array<Approver>;
    /**
     * Extra members merged into the pool after SLA timeout
     */
    elevationPool?: Array<Approver>;
};

export type Approver = {
    email: string;
    displayName: string;
    /**
     * e.g. Legal, Compliance, Department Head
     */
    role?: string;
};

export type ApprovalActorRequest = {
    /**
     * Optional comment; actor is the authenticated principal
     */
    comment?: string;
};

export type ApprovalDecisionRequest = {
    decision: 'approve' | 'reject';
    /**
     * Copied to `reviewcomment` (`kind=decision`) at decide-time. Required when
     * the step’s `commentPolicy` is `required_on_reject` (reject) or
     * `required_on_decision` (any decision). Missing required comment → 400
     * `comment_required`. History records a short label only.
     *
     */
    comment?: string;
};

export type ProcessSlaRequest = {
    /**
     * DEV/test clock override only. Production Cloud Flows omit this.
     * Invalid timestamps are rejected; non-DEV mocks ignore the field.
     *
     */
    now?: string;
};

export type PublishRequest = {
    /**
     * Allowlisted publish destination id. When omitted, the document type’s
     * default destination is used. Free-form SharePoint URLs are not accepted.
     *
     */
    publishDestinationId?: string;
    /**
     * Optional folder under the destination’s allowlisted root only.
     * Rejected when outside that root.
     *
     */
    folderPathOverride?: string;
};

export type CreateDocumentRequest = {
    title: string;
    /**
     * Document type id from the app config (drives approval chain + draft template)
     */
    documentType: string;
    /**
     * Unstructured request text that authors turn into a draft
     */
    freeformRequest: string;
    /**
     * Catalog key from `GET /control/priority-levels` (seed `low`, `normal`,
     * `high`, `mission_critical`). Unknown/inactive → 400 `unknown_priority`.
     *
     */
    priority?: string;
    /**
     * Required when the selected catalog row has `requiresReason`. Too short
     * → 400 `priority_reason_required`.
     *
     */
    priorityReason?: string;
    /**
     * Required when the document type has any active subtype. Unknown/wrong
     * type → 400 `unknown_subtype`. Missing when required → 400 `subtype_required`.
     *
     */
    documentSubtypeId?: string;
    /**
     * Values for optional per-type intake fields (`requestFields` on the
     * document type). Missing required keys → 400 `type_field_required`.
     *
     */
    typeFieldValues?: {
        [key: string]: string;
    };
    /**
     * Ignored. Trusted publish uses allowlisted destinations only; do not
     * send free-form SharePoint URLs.
     *
     *
     * @deprecated
     */
    requestedPublishSiteUrl?: string;
    /**
     * Ignored. Trusted publish uses allowlisted destinations only.
     *
     * @deprecated
     */
    requestedLibraryName?: string;
};

export type UpdateDraftRequest = {
    title: string;
    /**
     * Non-whitespace draft markdown
     */
    bodyMarkdown: string;
    /**
     * Optional summary; author is set from the authenticated principal
     */
    summary?: string;
    /**
     * Must match the document’s current `contentRevision`. Mismatch returns
     * 409 with code `revision_conflict`.
     *
     */
    expectedContentRevision: number;
};

export type DocumentSummary = {
    id: string;
    title: string;
    documentType: string;
    /**
     * Subtype key or id when the type requires one
     */
    documentSubtypeId?: string | null;
    status: DocumentStatus;
    requesterEmail: string;
    /**
     * Author collaboration team shared on create for co-editing drafts
     */
    collaboratorEmails?: Array<string>;
    /**
     * Catalog key (not a closed enum)
     */
    priority?: string;
    /**
     * Count of open authoritative decision comments (blocks resubmit)
     */
    openAuthoritativeCommentCount?: number;
    /**
     * Truncated newest decision-comment body (~140 chars) for inbox
     */
    lastReviewCommentPreview?: string | null;
    currentApproverEmail?: string | null;
    currentStepStatus?: ApprovalStepStatus | null;
    currentStepDueAt?: string | null;
    currentStepElevated?: boolean | null;
    /**
     * Eligible claimers when the active step is a pool queue
     */
    currentPoolEmails?: Array<string>;
    createdAt: string;
    updatedAt: string;
    /**
     * Incremented on each draft save
     */
    contentRevision?: number;
    /**
     * contentRevision frozen at submit-for-approval
     */
    submittedContentRevision?: number | null;
    /**
     * contentRevision of the artifact currently published
     */
    publishedContentRevision?: number | null;
    /**
     * Human-facing controlled document number (assigned on first publish)
     */
    documentNumber?: string | null;
    /**
     * Controlled version (1 on first publish; increments on superseding publish)
     */
    documentVersion?: number | null;
    /**
     * Prior published document this case will replace
     */
    supersedesDocumentId?: string | null;
    /**
     * Successor document that replaced this one
     */
    supersededByDocumentId?: string | null;
    /**
     * When this controlled version was published
     */
    publishedAt?: string | null;
};

export type ApprovalStep = {
    id: string;
    order: number;
    assignmentMode: ApprovalAssignmentMode;
    approverEmail?: string | null;
    approverDisplayName?: string | null;
    role?: string | null;
    status: ApprovalStepStatus;
    pool: Array<Approver>;
    elevationPool?: Array<Approver>;
    slaHours?: number | null;
    /**
     * Immutable SLA deadline set when the step activates
     */
    activateDueAt?: string | null;
    /**
     * Denormalized mirror of activateDueAt for inbox filters
     */
    dueAt?: string | null;
    claimedAt?: string | null;
    elevated: boolean;
    elevatedAt?: string | null;
    comment?: string | null;
    decidedAt?: string | null;
    /**
     * Document contentRevision at submit
     */
    submittedRevision?: number | null;
    /**
     * contentRevision recorded when this step approved
     */
    approvedRevision?: number | null;
    authorityLevel?: AuthorityLevel;
    commentPolicy?: CommentPolicy;
};

export type Document = DocumentSummary & {
    freeformRequest: string;
    draftBodyMarkdown?: string | null;
    draftSummary?: string | null;
    authorEmail?: string | null;
    contentRevision: number;
    submittedContentRevision?: number | null;
    publishedContentRevision?: number | null;
    priorityReason?: string | null;
    documentSubtypeId?: string | null;
    typeFieldValues?: {
        [key: string]: string;
    };
    /**
     * When true, the current approver/pool and author team may edit
     * draft markdown while the case is in review (dispatch-to-review types).
     *
     */
    allowReviewerDraftEdit?: boolean;
    approvalSteps: Array<ApprovalStep>;
    reviewComments: Array<ReviewComment>;
    history: Array<HistoryEvent>;
    publishedPdfUrl?: string | null;
    sharePointItemId?: string | null;
    requestedPublishSiteUrl?: string | null;
    requestedLibraryName?: string | null;
};

export type HistoryEvent = {
    id: string;
    at: string;
    actorEmail: string;
    action: string;
    message: string;
    /**
     * Optional link to the reviewcomment written at the same time
     */
    reviewCommentId?: string | null;
};

export type PublishResult = {
    document: Document;
    pdfFileName: string;
    sharePointUrl: string;
    sharePointItemId?: string;
    publishedAt: string;
    /**
     * True when the same revision was already published and no new file was created
     */
    idempotent?: boolean;
};

export type ControlChainStep = {
    order: number;
    assignmentMode: ApprovalAssignmentMode;
    role: string;
    slaHours?: number;
    assignee?: Approver;
    /**
     * Key of an approver pool for pool steps
     */
    poolKey?: string;
    elevationPoolKey?: string;
    authorityLevel?: AuthorityLevel;
    commentPolicy?: CommentPolicy;
};

export type ControlDocumentType = {
    id: string;
    label: string;
    description: string;
    requestHint: string;
    draftTemplate: string;
    folderPath?: string;
    authorTeamEmails: Array<string>;
    active: boolean;
    policyVersion: number;
    defaultDestinationId?: string | null;
    /**
     * Controlled document number prefix (e.g. POL)
     */
    numberPrefix?: string;
    /**
     * Pattern with {prefix}, {yyyy}, {seq:N}
     */
    numberPattern?: string;
    /**
     * Next sequence value for number allocation within sequenceYear
     */
    nextSequence?: number;
    /**
     * Calendar year for nextSequence; allocation resets when the year advances
     */
    sequenceYear?: number;
    approvalChain: Array<ControlChainStep>;
    /**
     * Active (or all, for Admin) subtypes belonging to this type
     */
    subtypes?: Array<DocumentSubtype>;
    /**
     * `dispatch_to_review` materializes the approval chain on create so
     * reviewers own the official document immediately.
     *
     */
    createWorkflow?: 'standard' | 'dispatch_to_review';
    /**
     * Optional intake fields collected on create (e.g. relevant systems)
     */
    requestFields?: Array<TypeRequestField>;
};

export type TypeRequestField = {
    key: string;
    label: string;
    kind: 'select';
    required?: boolean;
    options?: Array<{
        value: string;
        label: string;
    }>;
};

export type ControlDocumentTypeWrite = {
    id: string;
    label: string;
    description: string;
    requestHint: string;
    draftTemplate: string;
    folderPath?: string;
    authorTeamEmails?: Array<string>;
    active: boolean;
    policyVersion?: number;
    defaultDestinationId?: string | null;
    /**
     * Controlled document number prefix (e.g. POL)
     */
    numberPrefix?: string;
    /**
     * Pattern with {prefix}, {yyyy}, {seq:N}
     */
    numberPattern?: string;
    /**
     * Next sequence value for number allocation within sequenceYear
     */
    nextSequence?: number;
    /**
     * Calendar year for nextSequence (server-managed with nextSequence)
     */
    sequenceYear?: number;
    approvalChain: Array<ControlChainStep>;
    createWorkflow?: 'standard' | 'dispatch_to_review';
    requestFields?: Array<TypeRequestField>;
};

export type ControlApproverPool = {
    id: string;
    key: string;
    name: string;
    description: string;
    members: Array<Approver>;
};

export type ControlApproverPoolWrite = {
    name: string;
    description?: string;
    members: Array<Approver>;
};

export type ControlPublishDestination = {
    id: string;
    name: string;
    siteUrl: string;
    libraryName: string;
    folderPath: string;
    active: boolean;
};

export type ControlPublishDestinationWrite = {
    name: string;
    siteUrl: string;
    libraryName: string;
    folderPath: string;
    active: boolean;
};

export type ControlSettings = {
    /**
     * When true, Admin-authorized limited chain override at submit is allowed.
     * Default false — submit always materializes from control tables.
     *
     */
    allowApproverOverride: boolean;
    collaborationMode: string;
    namedElevationSemantics: 'convert_to_elevated_pool';
};

export type ControlFlowRun = {
    id: string;
    flowName: string;
    status: 'succeeded' | 'failed' | 'running';
    at: string;
    message: string;
};

export type AuthorityLevel = 'advisory' | 'standard' | 'authoritative';

export type CommentPolicy = 'optional' | 'required_on_reject' | 'required_on_decision';

export type ReviewCommentKind = 'decision' | 'submission' | 'author_response' | 'acknowledgement';

export type ReviewCommentStatus = 'open' | 'addressed' | 'acknowledged' | 'voided';

export type ReviewComment = {
    id: string;
    kind: ReviewCommentKind;
    authorityLevel: AuthorityLevel;
    status: ReviewCommentStatus;
    body: string;
    actorEmail: string;
    actorDisplayName: string;
    role?: string | null;
    sourceStepId?: string | null;
    sourceStepOrder?: number | null;
    submittedContentRevision?: number | null;
    inReplyTo?: string | null;
    createdAt: string;
};

export type ReviewCommentRespondRequest = {
    /**
     * Author reply. Authoritative comments require ≥ 20 non-whitespace characters.
     */
    body: string;
};

export type UpdatePriorityRequest = {
    priority: string;
    priorityReason?: string | null;
};

export type PriorityLevel = {
    id: string;
    key: string;
    label: string;
    rank: number;
    color: 'default' | 'info' | 'warning' | 'error';
    requiresReason: boolean;
    minReasonLength: number;
    reasonHint?: string;
    active: boolean;
    /**
     * Stored unused in v1; do not apply to activateDueAt
     */
    slaHoursMultiplier?: number | null;
};

export type PriorityLevelWrite = {
    key: string;
    label: string;
    rank: number;
    color: 'default' | 'info' | 'warning' | 'error';
    requiresReason: boolean;
    minReasonLength?: number;
    reasonHint?: string;
    active: boolean;
    slaHoursMultiplier?: number | null;
};

export type DocumentSubtype = {
    id: string;
    key: string;
    label: string;
    description?: string;
    documentTypeId: string;
    active: boolean;
    requestHint?: string | null;
    draftScaffold?: string | null;
    numberPrefix?: string | null;
    usesOwnChain: boolean;
    /**
     * Required and non-empty when usesOwnChain is true
     */
    approvalChain?: Array<ControlChainStep>;
};

export type DocumentSubtypeWrite = {
    key: string;
    label: string;
    description?: string;
    documentTypeId: string;
    active: boolean;
    requestHint?: string | null;
    draftScaffold?: string | null;
    numberPrefix?: string | null;
    usesOwnChain: boolean;
    approvalChain?: Array<ControlChainStep>;
};

export type Error = {
    message: string;
    code?: string;
};

export type DocumentId = string;

export type CommentId = string;

export type GetPrincipalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/principal';
};

export type GetPrincipalErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
};

export type GetPrincipalError = GetPrincipalErrors[keyof GetPrincipalErrors];

export type GetPrincipalResponses = {
    /**
     * Caller principal with roles
     */
    200: Principal;
};

export type GetPrincipalResponse = GetPrincipalResponses[keyof GetPrincipalResponses];

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        status?: DocumentStatus;
        /**
         * Filter by configured document type id (policy, sop, …)
         */
        documentType?: string;
        /**
         * Free-text search across title and request body
         */
        q?: string;
        /**
         * Inbox persona filter (server-side; mirrors client personas)
         */
        persona?: 'all' | 'waiting_on_me' | 'available_in_pool' | 'my_requests' | 'needs_draft' | 'ready_to_publish';
        /**
         * Max items to return (default 50, max 200)
         */
        limit?: number;
        /**
         * Opaque pagination cursor from a prior nextCursor
         */
        cursor?: string;
    };
    url: '/documents';
};

export type ListDocumentsErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type ListDocumentsError = ListDocumentsErrors[keyof ListDocumentsErrors];

export type ListDocumentsResponses = {
    /**
     * Document list
     */
    200: {
        items: Array<DocumentSummary>;
        /**
         * Pass as cursor on the next request; null when no more pages
         */
        nextCursor?: string;
    };
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type CreateDocumentRequestData = {
    body: CreateDocumentRequest;
    path?: never;
    query?: never;
    url: '/documents';
};

export type CreateDocumentRequestErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
};

export type CreateDocumentRequestError = CreateDocumentRequestErrors[keyof CreateDocumentRequestErrors];

export type CreateDocumentRequestResponses = {
    /**
     * Created request
     */
    201: Document;
};

export type CreateDocumentRequestResponse = CreateDocumentRequestResponses[keyof CreateDocumentRequestResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}';
};

export type GetDocumentErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Document detail
     */
    200: Document;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type UpdateDocumentDraftData = {
    body: UpdateDraftRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/draft';
};

export type UpdateDocumentDraftErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type UpdateDocumentDraftError = UpdateDocumentDraftErrors[keyof UpdateDocumentDraftErrors];

export type UpdateDocumentDraftResponses = {
    /**
     * Updated draft
     */
    200: Document;
};

export type UpdateDocumentDraftResponse = UpdateDocumentDraftResponses[keyof UpdateDocumentDraftResponses];

export type SubmitForApprovalData = {
    body: SubmitForApprovalRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/submit-for-approval';
};

export type SubmitForApprovalErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type SubmitForApprovalError = SubmitForApprovalErrors[keyof SubmitForApprovalErrors];

export type SubmitForApprovalResponses = {
    /**
     * Submitted for approval
     */
    200: Document;
};

export type SubmitForApprovalResponse = SubmitForApprovalResponses[keyof SubmitForApprovalResponses];

export type WithdrawAndReviseData = {
    body?: ApprovalActorRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/withdraw-and-revise';
};

export type WithdrawAndReviseErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type WithdrawAndReviseError = WithdrawAndReviseErrors[keyof WithdrawAndReviseErrors];

export type WithdrawAndReviseResponses = {
    /**
     * Document returned to drafting
     */
    200: Document;
};

export type WithdrawAndReviseResponse = WithdrawAndReviseResponses[keyof WithdrawAndReviseResponses];

export type DecideApprovalStepData = {
    body: ApprovalDecisionRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/decision';
};

export type DecideApprovalStepErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type DecideApprovalStepError = DecideApprovalStepErrors[keyof DecideApprovalStepErrors];

export type DecideApprovalStepResponses = {
    /**
     * Updated document after decision
     */
    200: Document;
};

export type DecideApprovalStepResponse = DecideApprovalStepResponses[keyof DecideApprovalStepResponses];

export type RespondToReviewCommentData = {
    body: ReviewCommentRespondRequest;
    path: {
        documentId: string;
        commentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/review-comments/{commentId}/respond';
};

export type RespondToReviewCommentErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type RespondToReviewCommentError = RespondToReviewCommentErrors[keyof RespondToReviewCommentErrors];

export type RespondToReviewCommentResponses = {
    /**
     * Document with updated review comments
     */
    200: Document;
};

export type RespondToReviewCommentResponse = RespondToReviewCommentResponses[keyof RespondToReviewCommentResponses];

export type AcknowledgeReviewCommentData = {
    body?: {
        comment?: string;
    };
    path: {
        documentId: string;
        commentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/review-comments/{commentId}/acknowledge';
};

export type AcknowledgeReviewCommentErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type AcknowledgeReviewCommentError = AcknowledgeReviewCommentErrors[keyof AcknowledgeReviewCommentErrors];

export type AcknowledgeReviewCommentResponses = {
    /**
     * Document with updated review comments
     */
    200: Document;
};

export type AcknowledgeReviewCommentResponse = AcknowledgeReviewCommentResponses[keyof AcknowledgeReviewCommentResponses];

export type UpdateDocumentPriorityData = {
    body: UpdatePriorityRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/priority';
};

export type UpdateDocumentPriorityErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type UpdateDocumentPriorityError = UpdateDocumentPriorityErrors[keyof UpdateDocumentPriorityErrors];

export type UpdateDocumentPriorityResponses = {
    /**
     * Document with updated priority
     */
    200: Document;
};

export type UpdateDocumentPriorityResponse = UpdateDocumentPriorityResponses[keyof UpdateDocumentPriorityResponses];

export type ClaimApprovalStepData = {
    body: ApprovalActorRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/claim';
};

export type ClaimApprovalStepErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type ClaimApprovalStepError = ClaimApprovalStepErrors[keyof ClaimApprovalStepErrors];

export type ClaimApprovalStepResponses = {
    /**
     * Step claimed
     */
    200: Document;
};

export type ClaimApprovalStepResponse = ClaimApprovalStepResponses[keyof ClaimApprovalStepResponses];

export type ReleaseApprovalStepData = {
    body: ApprovalActorRequest;
    path: {
        documentId: string;
        stepId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/{stepId}/release';
};

export type ReleaseApprovalStepErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type ReleaseApprovalStepError = ReleaseApprovalStepErrors[keyof ReleaseApprovalStepErrors];

export type ReleaseApprovalStepResponses = {
    /**
     * Step released back to queue
     */
    200: Document;
};

export type ReleaseApprovalStepResponse = ReleaseApprovalStepResponses[keyof ReleaseApprovalStepResponses];

export type ProcessApprovalSlaData = {
    body?: ProcessSlaRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/approvals/process-sla';
};

export type ProcessApprovalSlaErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type ProcessApprovalSlaError = ProcessApprovalSlaErrors[keyof ProcessApprovalSlaErrors];

export type ProcessApprovalSlaResponses = {
    /**
     * Document after SLA processing
     */
    200: Document;
};

export type ProcessApprovalSlaResponse = ProcessApprovalSlaResponses[keyof ProcessApprovalSlaResponses];

export type PublishDocumentPdfData = {
    body: PublishRequest;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/publish';
};

export type PublishDocumentPdfErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type PublishDocumentPdfError = PublishDocumentPdfErrors[keyof PublishDocumentPdfErrors];

export type PublishDocumentPdfResponses = {
    /**
     * Published document (or existing artifact for same revision)
     */
    200: PublishResult;
};

export type PublishDocumentPdfResponse = PublishDocumentPdfResponses[keyof PublishDocumentPdfResponses];

export type SupersedeDocumentData = {
    body?: {
        comment?: string;
    };
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/supersede';
};

export type SupersedeDocumentErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type SupersedeDocumentError = SupersedeDocumentErrors[keyof SupersedeDocumentErrors];

export type SupersedeDocumentResponses = {
    /**
     * Successor document created
     */
    201: Document;
};

export type SupersedeDocumentResponse = SupersedeDocumentResponses[keyof SupersedeDocumentResponses];

export type AbandonSupersedeData = {
    body?: {
        comment?: string;
    };
    path: {
        documentId: string;
    };
    query?: never;
    url: '/documents/{documentId}/abandon-supersede';
};

export type AbandonSupersedeErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type AbandonSupersedeError = AbandonSupersedeErrors[keyof AbandonSupersedeErrors];

export type AbandonSupersedeResponses = {
    /**
     * Successor abandoned
     */
    200: Document;
};

export type AbandonSupersedeResponse = AbandonSupersedeResponses[keyof AbandonSupersedeResponses];

export type ListLibraryDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search number, title, or type
         */
        q?: string;
        documentType?: string;
        includeSuperseded?: boolean;
        /**
         * Max items to return (default 50, max 200)
         */
        limit?: number;
        /**
         * Opaque pagination cursor from a prior nextCursor
         */
        cursor?: string;
    };
    url: '/library';
};

export type ListLibraryDocumentsErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
};

export type ListLibraryDocumentsError = ListLibraryDocumentsErrors[keyof ListLibraryDocumentsErrors];

export type ListLibraryDocumentsResponses = {
    /**
     * Library list
     */
    200: {
        items: Array<DocumentSummary>;
        /**
         * Pass as cursor on the next request; null when no more pages
         */
        nextCursor?: string;
    };
};

export type ListLibraryDocumentsResponse = ListLibraryDocumentsResponses[keyof ListLibraryDocumentsResponses];

export type GetDocumentByNumberData = {
    body?: never;
    path: {
        documentNumber: string;
    };
    query?: never;
    url: '/documents/by-number/{documentNumber}';
};

export type GetDocumentByNumberErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type GetDocumentByNumberError = GetDocumentByNumberErrors[keyof GetDocumentByNumberErrors];

export type GetDocumentByNumberResponses = {
    /**
     * Current published document for this number
     */
    200: Document;
};

export type GetDocumentByNumberResponse = GetDocumentByNumberResponses[keyof GetDocumentByNumberResponses];

export type ListDocumentTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/document-types';
};

export type ListDocumentTypesResponses = {
    /**
     * Document type catalog
     */
    200: {
        items: Array<ControlDocumentType>;
    };
};

export type ListDocumentTypesResponse = ListDocumentTypesResponses[keyof ListDocumentTypesResponses];

export type CreateDocumentTypeData = {
    body: ControlDocumentTypeWrite;
    path?: never;
    query?: never;
    url: '/control/document-types';
};

export type CreateDocumentTypeErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type CreateDocumentTypeError = CreateDocumentTypeErrors[keyof CreateDocumentTypeErrors];

export type CreateDocumentTypeResponses = {
    /**
     * Created
     */
    201: ControlDocumentType;
};

export type CreateDocumentTypeResponse = CreateDocumentTypeResponses[keyof CreateDocumentTypeResponses];

export type DeactivateDocumentTypeData = {
    body?: never;
    path: {
        typeId: string;
    };
    query?: never;
    url: '/control/document-types/{typeId}';
};

export type DeactivateDocumentTypeErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeactivateDocumentTypeError = DeactivateDocumentTypeErrors[keyof DeactivateDocumentTypeErrors];

export type DeactivateDocumentTypeResponses = {
    /**
     * Deactivated
     */
    200: ControlDocumentType;
};

export type DeactivateDocumentTypeResponse = DeactivateDocumentTypeResponses[keyof DeactivateDocumentTypeResponses];

export type GetDocumentTypeConfigData = {
    body?: never;
    path: {
        typeId: string;
    };
    query?: never;
    url: '/control/document-types/{typeId}';
};

export type GetDocumentTypeConfigErrors = {
    /**
     * Resource not found
     */
    404: Error;
};

export type GetDocumentTypeConfigError = GetDocumentTypeConfigErrors[keyof GetDocumentTypeConfigErrors];

export type GetDocumentTypeConfigResponses = {
    /**
     * Document type
     */
    200: ControlDocumentType;
};

export type GetDocumentTypeConfigResponse = GetDocumentTypeConfigResponses[keyof GetDocumentTypeConfigResponses];

export type UpdateDocumentTypeData = {
    body: ControlDocumentTypeWrite;
    path: {
        typeId: string;
    };
    query?: never;
    url: '/control/document-types/{typeId}';
};

export type UpdateDocumentTypeErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type UpdateDocumentTypeError = UpdateDocumentTypeErrors[keyof UpdateDocumentTypeErrors];

export type UpdateDocumentTypeResponses = {
    /**
     * Updated
     */
    200: ControlDocumentType;
};

export type UpdateDocumentTypeResponse = UpdateDocumentTypeResponses[keyof UpdateDocumentTypeResponses];

export type ListApproverPoolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/approver-pools';
};

export type ListApproverPoolsErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type ListApproverPoolsError = ListApproverPoolsErrors[keyof ListApproverPoolsErrors];

export type ListApproverPoolsResponses = {
    /**
     * Pools
     */
    200: {
        items: Array<ControlApproverPool>;
    };
};

export type ListApproverPoolsResponse = ListApproverPoolsResponses[keyof ListApproverPoolsResponses];

export type CreateApproverPoolData = {
    body: ControlApproverPoolWrite;
    path?: never;
    query?: never;
    url: '/control/approver-pools';
};

export type CreateApproverPoolErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type CreateApproverPoolError = CreateApproverPoolErrors[keyof CreateApproverPoolErrors];

export type CreateApproverPoolResponses = {
    /**
     * Created
     */
    201: ControlApproverPool;
};

export type CreateApproverPoolResponse = CreateApproverPoolResponses[keyof CreateApproverPoolResponses];

export type DeleteApproverPoolData = {
    body?: never;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/control/approver-pools/{poolId}';
};

export type DeleteApproverPoolErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
    /**
     * Invalid state transition
     */
    409: Error;
};

export type DeleteApproverPoolError = DeleteApproverPoolErrors[keyof DeleteApproverPoolErrors];

export type DeleteApproverPoolResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteApproverPoolResponse = DeleteApproverPoolResponses[keyof DeleteApproverPoolResponses];

export type UpdateApproverPoolData = {
    body: ControlApproverPoolWrite;
    path: {
        poolId: string;
    };
    query?: never;
    url: '/control/approver-pools/{poolId}';
};

export type UpdateApproverPoolErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type UpdateApproverPoolError = UpdateApproverPoolErrors[keyof UpdateApproverPoolErrors];

export type UpdateApproverPoolResponses = {
    /**
     * Updated
     */
    200: ControlApproverPool;
};

export type UpdateApproverPoolResponse = UpdateApproverPoolResponses[keyof UpdateApproverPoolResponses];

export type ListPublishDestinationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/publish-destinations';
};

export type ListPublishDestinationsResponses = {
    /**
     * Destinations
     */
    200: {
        items: Array<ControlPublishDestination>;
    };
};

export type ListPublishDestinationsResponse = ListPublishDestinationsResponses[keyof ListPublishDestinationsResponses];

export type CreatePublishDestinationData = {
    body: ControlPublishDestinationWrite;
    path?: never;
    query?: never;
    url: '/control/publish-destinations';
};

export type CreatePublishDestinationErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type CreatePublishDestinationError = CreatePublishDestinationErrors[keyof CreatePublishDestinationErrors];

export type CreatePublishDestinationResponses = {
    /**
     * Created
     */
    201: ControlPublishDestination;
};

export type CreatePublishDestinationResponse = CreatePublishDestinationResponses[keyof CreatePublishDestinationResponses];

export type DeactivatePublishDestinationData = {
    body?: never;
    path: {
        destinationId: string;
    };
    query?: never;
    url: '/control/publish-destinations/{destinationId}';
};

export type DeactivatePublishDestinationErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeactivatePublishDestinationError = DeactivatePublishDestinationErrors[keyof DeactivatePublishDestinationErrors];

export type DeactivatePublishDestinationResponses = {
    /**
     * Deactivated
     */
    200: ControlPublishDestination;
};

export type DeactivatePublishDestinationResponse = DeactivatePublishDestinationResponses[keyof DeactivatePublishDestinationResponses];

export type UpdatePublishDestinationData = {
    body: ControlPublishDestinationWrite;
    path: {
        destinationId: string;
    };
    query?: never;
    url: '/control/publish-destinations/{destinationId}';
};

export type UpdatePublishDestinationErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type UpdatePublishDestinationError = UpdatePublishDestinationErrors[keyof UpdatePublishDestinationErrors];

export type UpdatePublishDestinationResponses = {
    /**
     * Updated
     */
    200: ControlPublishDestination;
};

export type UpdatePublishDestinationResponse = UpdatePublishDestinationResponses[keyof UpdatePublishDestinationResponses];

export type GetControlSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/settings';
};

export type GetControlSettingsErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type GetControlSettingsError = GetControlSettingsErrors[keyof GetControlSettingsErrors];

export type GetControlSettingsResponses = {
    /**
     * Settings
     */
    200: ControlSettings;
};

export type GetControlSettingsResponse = GetControlSettingsResponses[keyof GetControlSettingsResponses];

export type UpdateControlSettingsData = {
    body: ControlSettings;
    path?: never;
    query?: never;
    url: '/control/settings';
};

export type UpdateControlSettingsErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type UpdateControlSettingsError = UpdateControlSettingsErrors[keyof UpdateControlSettingsErrors];

export type UpdateControlSettingsResponses = {
    /**
     * Updated settings
     */
    200: ControlSettings;
};

export type UpdateControlSettingsResponse = UpdateControlSettingsResponses[keyof UpdateControlSettingsResponses];

export type ListFlowRunsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/flow-runs';
};

export type ListFlowRunsErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type ListFlowRunsError = ListFlowRunsErrors[keyof ListFlowRunsErrors];

export type ListFlowRunsResponses = {
    /**
     * Flow runs
     */
    200: {
        items: Array<ControlFlowRun>;
    };
};

export type ListFlowRunsResponse = ListFlowRunsResponses[keyof ListFlowRunsResponses];

export type ListPriorityLevelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/control/priority-levels';
};

export type ListPriorityLevelsErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
};

export type ListPriorityLevelsError = ListPriorityLevelsErrors[keyof ListPriorityLevelsErrors];

export type ListPriorityLevelsResponses = {
    /**
     * Priority catalog
     */
    200: {
        items: Array<PriorityLevel>;
    };
};

export type ListPriorityLevelsResponse = ListPriorityLevelsResponses[keyof ListPriorityLevelsResponses];

export type CreatePriorityLevelData = {
    body: PriorityLevelWrite;
    path?: never;
    query?: never;
    url: '/control/priority-levels';
};

export type CreatePriorityLevelErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type CreatePriorityLevelError = CreatePriorityLevelErrors[keyof CreatePriorityLevelErrors];

export type CreatePriorityLevelResponses = {
    /**
     * Created
     */
    201: PriorityLevel;
};

export type CreatePriorityLevelResponse = CreatePriorityLevelResponses[keyof CreatePriorityLevelResponses];

export type UpdatePriorityLevelData = {
    body: PriorityLevelWrite;
    path: {
        priorityId: string;
    };
    query?: never;
    url: '/control/priority-levels/{priorityId}';
};

export type UpdatePriorityLevelErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type UpdatePriorityLevelError = UpdatePriorityLevelErrors[keyof UpdatePriorityLevelErrors];

export type UpdatePriorityLevelResponses = {
    /**
     * Updated
     */
    200: PriorityLevel;
};

export type UpdatePriorityLevelResponse = UpdatePriorityLevelResponses[keyof UpdatePriorityLevelResponses];

export type ListDocumentSubtypesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by parent document type id
         */
        documentType?: string;
    };
    url: '/control/document-subtypes';
};

export type ListDocumentSubtypesErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
};

export type ListDocumentSubtypesError = ListDocumentSubtypesErrors[keyof ListDocumentSubtypesErrors];

export type ListDocumentSubtypesResponses = {
    /**
     * Subtype catalog
     */
    200: {
        items: Array<DocumentSubtype>;
    };
};

export type ListDocumentSubtypesResponse = ListDocumentSubtypesResponses[keyof ListDocumentSubtypesResponses];

export type CreateDocumentSubtypeData = {
    body: DocumentSubtypeWrite;
    path?: never;
    query?: never;
    url: '/control/document-subtypes';
};

export type CreateDocumentSubtypeErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
};

export type CreateDocumentSubtypeError = CreateDocumentSubtypeErrors[keyof CreateDocumentSubtypeErrors];

export type CreateDocumentSubtypeResponses = {
    /**
     * Created
     */
    201: DocumentSubtype;
};

export type CreateDocumentSubtypeResponse = CreateDocumentSubtypeResponses[keyof CreateDocumentSubtypeResponses];

export type DeactivateDocumentSubtypeData = {
    body?: never;
    path: {
        subtypeId: string;
    };
    query?: never;
    url: '/control/document-subtypes/{subtypeId}';
};

export type DeactivateDocumentSubtypeErrors = {
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type DeactivateDocumentSubtypeError = DeactivateDocumentSubtypeErrors[keyof DeactivateDocumentSubtypeErrors];

export type DeactivateDocumentSubtypeResponses = {
    /**
     * Deactivated
     */
    200: DocumentSubtype;
};

export type DeactivateDocumentSubtypeResponse = DeactivateDocumentSubtypeResponses[keyof DeactivateDocumentSubtypeResponses];

export type UpdateDocumentSubtypeData = {
    body: DocumentSubtypeWrite;
    path: {
        subtypeId: string;
    };
    query?: never;
    url: '/control/document-subtypes/{subtypeId}';
};

export type UpdateDocumentSubtypeErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Missing or invalid caller principal
     */
    401: Error;
    /**
     * Caller is not allowed to perform this action
     */
    403: Error;
    /**
     * Resource not found
     */
    404: Error;
};

export type UpdateDocumentSubtypeError = UpdateDocumentSubtypeErrors[keyof UpdateDocumentSubtypeErrors];

export type UpdateDocumentSubtypeResponses = {
    /**
     * Updated
     */
    200: DocumentSubtype;
};

export type UpdateDocumentSubtypeResponse = UpdateDocumentSubtypeResponses[keyof UpdateDocumentSubtypeResponses];
